services:
  mysql:
    image: mysql:8.0
    container_name: attractions_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Bangkok
    ports:
      - "127.0.0.1:${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks: [stack]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 256M
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    depends_on: [mysql]
    networks: [stack]

  api:
    build: ./01_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Bangkok
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on: [mysql]
    networks: [stack]

  frontend:
    build: ./02_frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_HOST=http://api:3000 
    ports:
      - "${FRONTEND_PORT:-3030}:3030"
    depends_on: [api]
    networks: [stack]

volumes:
  mysql_data:

networks:
  stack:
    driver: bridge
